server.port=8081
spring.datasource.url=jdbc:h2:mem:dev_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
#logging.level.org.springframework=DEBUG
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=juanfajardoreyes@hotmail.com
spring.mail.password=lozwhsdekeysbwkc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
